// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxNlPbv9ue2MySO65VHC9EoJKu6LOyFc',
    appId: '1:900458994944:web:8b6a3f0431be4146d8a7e5',
    messagingSenderId: '900458994944',
    projectId: 'spotify-378c3',
    authDomain: 'spotify-378c3.firebaseapp.com',
    storageBucket: 'spotify-378c3.firebasestorage.app',
    measurementId: 'G-G1CSJSP704',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9pVLO_26aY0Fj3bDlfGJJcIqv2hOxUcQ',
    appId: '1:900458994944:android:37367f1bb6ebba4dd8a7e5',
    messagingSenderId: '900458994944',
    projectId: 'spotify-378c3',
    storageBucket: 'spotify-378c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fw4c35mY-CiNrpKbdp0EhfUIDLpTya4',
    appId: '1:900458994944:ios:f9689572b0915dc4d8a7e5',
    messagingSenderId: '900458994944',
    projectId: 'spotify-378c3',
    storageBucket: 'spotify-378c3.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_fw4c35mY-CiNrpKbdp0EhfUIDLpTya4',
    appId: '1:900458994944:ios:f9689572b0915dc4d8a7e5',
    messagingSenderId: '900458994944',
    projectId: 'spotify-378c3',
    storageBucket: 'spotify-378c3.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLxNlPbv9ue2MySO65VHC9EoJKu6LOyFc',
    appId: '1:900458994944:web:1afecf48c87b4711d8a7e5',
    messagingSenderId: '900458994944',
    projectId: 'spotify-378c3',
    authDomain: 'spotify-378c3.firebaseapp.com',
    storageBucket: 'spotify-378c3.firebasestorage.app',
    measurementId: 'G-QRW8RC3DNE',
  );
}
